name: Java CI with Maven and Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build with Maven
      run: mvn clean install
 
    - name: List files in target directory
      run: |
        pwd
        ls -l ./target/
    - name: Verify JAR file before deployment
      run: |
        ls -l /home/runner/work/locationproducerservice/locationproducerservice/target/
        ls -l /home/runner/work/
        ls -l /home/runner/work/_temp/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: List files in target directory
      run: |
        pwd
        ls -l /home/runner/work/
        ls -l /home/runner/work/_temp/
    - name: Search for JAR in _temp directory
      run: find /home/runner/ -name "locationproducerservice-0.0.1-SNAPSHOT.jar"


    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: locationpublisherservice
        slot-name: 'production'
        package: /home/runner/work/locationproducerservice/locationproducerservice/locationproducerservice-0.0.1-SNAPSHOT.jar
    - name: Logout from Azure
      run: az logout
